### ISSUE TITLE
Return client and job id even thougth there has been no modifications

### ISSUE THREAD

**Issue by nredobi** [elkarbackup/ansible-collection-elkarbackup#3]
We want to return the client and job id even thougth there has been no modifications (like it does when there are changes).

**Comment by elacunza** [comment]
This should be fixed in tag 0.1.3_2 486d44f698d1e93eb9c013b8be6b118a6206e12d , released to galaxy: https://galaxy.ansible.com/elkarbackup/elkarbackup as version 0.1.3
